# Generated by Django 4.1.1 on 2023-02-18 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("violence_data_page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                ("video_id", models.AutoField(primary_key=True, serialize=False)),
                ("video_date", models.DateField()),
                ("video_start_time", models.TimeField()),
                ("video_path", models.TextField(blank=True, null=True)),
                (
                    "video_isviolence",
                    models.CharField(
                        blank=True,
                        db_column="video_isViolence",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "video_school",
                    models.ForeignKey(
                        db_column="video_school",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="violence_data_page.school",
                    ),
                ),
            ],
            options={
                "db_table": "Video",
                "managed": True,
            },
        ),
    ]
