# Generated by Django 4.1.1 on 2023-02-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_profile_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="profile_url",
            new_name="profile_img",
        ),
    ]
