# Generated by Django 4.1.1 on 2023-02-01 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("region_id", models.AutoField(primary_key=True, serialize=False)),
                ("region_si", models.CharField(max_length=20)),
                ("region_gu", models.CharField(max_length=20)),
                (
                    "region_singleParent",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "region_basicRecipient",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "region_incomeMedium",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                (
                    "region_incomeHigh",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                ("region_adultGame", models.IntegerField(verbose_name=11)),
                (
                    "region_homeViolence",
                    models.DecimalField(decimal_places=9, max_digits=10),
                ),
                (
                    "region_dateViolence",
                    models.DecimalField(decimal_places=10, max_digits=11),
                ),
                (
                    "region_averageIncome",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "region_multicultural",
                    models.DecimalField(decimal_places=9, max_digits=11),
                ),
            ],
            options={
                "db_table": "Region",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("school_id", models.AutoField(primary_key=True, serialize=False)),
                ("school_name", models.CharField(max_length=30)),
                ("school_address2", models.CharField(max_length=100, unique=True)),
                (
                    "school_address1",
                    models.ForeignKey(
                        db_column="school_address1",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="violence_data_page.region",
                    ),
                ),
            ],
            options={
                "db_table": "School",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SchoolData",
            fields=[
                ("school_data_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "school_data_education",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "school_data_score",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                ("school_data_cluster", models.IntegerField(verbose_name=11)),
                ("school_danger_level", models.CharField(max_length=10)),
                (
                    "school_data_school",
                    models.ForeignKey(
                        db_column="school_data_school",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="violence_data_page.school",
                    ),
                ),
            ],
            options={
                "db_table": "School_data",
                "managed": True,
            },
        ),
    ]
