# Generated by Django 4.1.1 on 2023-02-18 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                ("region_id", models.AutoField(primary_key=True, serialize=False)),
                ("region_name", models.CharField(max_length=150)),
                ("region_environment_score", models.FloatField()),
            ],
            options={
                "db_table": "Region",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                ("school_id", models.AutoField(primary_key=True, serialize=False)),
                ("school_name", models.CharField(max_length=30)),
                ("school_address2", models.CharField(max_length=100, unique=True)),
                (
                    "school_address1",
                    models.ForeignKey(
                        db_column="school_address1",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="violence_data_page.region",
                    ),
                ),
            ],
            options={
                "db_table": "School",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SchoolData",
            fields=[
                ("school_data_id", models.AutoField(primary_key=True, serialize=False)),
                ("school_data_harzard_score", models.IntegerField()),
                ("school_data_alleviate_score", models.IntegerField()),
                ("school_data_total_score", models.FloatField()),
                ("school_danger_danger_degree", models.CharField(max_length=10)),
                (
                    "school_data_school",
                    models.ForeignKey(
                        db_column="school_data_school",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="violence_data_page.school",
                    ),
                ),
            ],
            options={
                "db_table": "School_data",
                "managed": True,
            },
        ),
    ]
